export const products = [
    {
      id: 1,
      name: 'Платье-миди с расклешенной юбкой',
      image: process.env.PUBLIC_URL + '/img/id1.png',
      code: '82039-11',
      size: 44,
      color: "синий",
      quantity: 1,
      price: 2450,
    },
    {
      id: 2,
      name: 'Туфли женские украшенные кружевными вставками',
      image: process.env.PUBLIC_URL + '/img/id2.png',
      code: '13524 - 01',
      size: 38,
      color: "черный",
      quantity: 1,
      price: 2450,
    },
    {
      id: 3,
      name: 'Платье-миди',
      image: process.env.PUBLIC_URL + '/img/id3.png',
      code: '75039',
      size: 44,
      color: "белый",
      quantity: 1,
      price: 2450,
    },
    {
      id: 4,
      name: 'Платье-миди',
      image: process.env.PUBLIC_URL + '/img/id3.png',
      code: '75039',
      size: 46,
      color: "белый",
      quantity: 1,
      price: 2450,
    },
  ];